### PR TITLE
Add preference to choose the display to show the website on

### PR DESCRIPTION
**Pull request by sindresorhus**
This is the first part of #2. It will let you choose a display to show the website on. It does not let you show the same website on multiple screens or different websites on multiple screens.

Screenshot 2020-01-10 at 17 52 08

### CODE REVIEW

**Comment by sindresorhus** [comment]
@lacking-utility @firrae @ianiv Could you try out the below build and let me know how it works?

[Plash-multiple-display.zip](https://github.com/sindresorhus/Plash/files/4045238/Plash-multiple-display.zip)
*(It's not notarized, so you need to right-click and choose "Open" instead of double-clicking)*

**Comment by firrae** [comment]
@sindresorhus This seems to be working for me, I'll test if I still get the issue from #23 with this build later this afternoon.

**Comment by ianiv** [comment]
Above build works for me, switching from one monitor to the other with no issues so far.

**Comment by lacking-utility** [comment]
Build works for me too, and with the added wrinkle that I've got a MBP connected to a Thunderbolt Display and an eGPU with a Radeon RX 5700 and 3 additional monitors. Can switch the site amongst the external monitors with no problems.

**Pull request merged**
