### PR TITLE
Support multiple websites

### LINKED ISSUE #24: Save multiple sites and possibly toggle them with ⌘ + number value
It would be great to be able to save multiple website and switch them like tabs with ⌘ + Numeric key!

### PR DESCRIPTION
**Pull request by sindresorhus**
You can now add multiple websites and switch through them in the menu or through global keyboard shortcuts. Some of the website-related preferences have moved into the website add/edit dialog.

I have not implemented auto-switching. That can happen later.

Test build: [Plash.app.zip](https://github.com/sindresorhus/Plash/files/6201826/Plash-2.zip)\
(The websites you add here will not be available later on in the App Store version)

Fixes #24

---

Screen Shot 2021-03-24 at 21 41 43
Screen Shot 2021-03-24 at 21 41 51
Screen Shot 2021-03-24 at 21 41 58

### CODE REVIEW

**Comment by sindresorhus** [comment]
@withoutwax Would you be able to test? I'm happy with any kind of nitpicking. I didn't add Command+n as we cannot do that globally. Instead, I added the ability to set global keyboard shortcuts for next/previous website. I'm open to ideas for other things that would make the experience better.

**Comment by sindresorhus** [comment]
// @thatrobotdev In case you want to help test.

**Comment by ClaireBookworm** [comment]
I'd love to help test!

**Comment by sindresorhus** [comment]
In case it's not clear, there's a link to the test build at the top.

**Comment by ced404** [comment]
Really nice feature!

For some reason the "previous website" shortcut is not working.
I tried different shortcuts but still.
I can loop through websites with the "next website" shortcut.

screenshot 2021-03-24 à 19 00 54

**Comment by ced404** [comment]
Maybe we could have an option to choose the default website at startup?
It would default to the last used if none is set up (as it is right now).

**Comment by sindresorhus** [comment]
> For some reason the "previous website" shortcut is not working.

Good catch. Just a typo: https://github.com/sindresorhus/Plash/pull/74/commits/59d21c128911f06ca4634c36e8ab2d06a0593b7c

**Comment by sindresorhus** [comment]
> Maybe we could have an option to choose the default website at startup?

Any reason you don't want it to just show the previous one? I don't add preferences lightly, so there must be some good use-cases.

**Comment by ced404** [comment]
I understand, maybe it's not that important. 
It is to reset the desktop to my favorite site when login back on. Like closing the session would reset to some preferred defaults (if any).

**Comment by raguay** [comment]
The website list box doesn't show up good on my computer.

MacBook Air 13" 2017
macOS 10.15.7 (19H524)
Plash Version 1.8.0-multiplewebsites (12)

1498F704-4CAD-4192-913F-FE5388C86F48

This is with just my local website loaded. This next one is with a few more sites added:

7BC09A58-5664-4235-8530-0EFD1F967D1B

As already mentioned, the previous site hotkey isn't working.

**Comment by withoutwax** [comment]
@sindresorhus Hey Sindre! Sorry for the late response! Yes - I'm more than happy to test and give any feedback necessary!

**Comment by withoutwax** [comment]
> @withoutwax Would you be able to test? I'm happy with any kind of nitpicking. I didn't add Command+n as we cannot do that globally. Instead, I added the ability to set global keyboard shortcuts for next/previous website. I'm open to ideas for other things that would make the experience better.

@sindresorhus Hey Sindre! Sorry for the late response! Yes - I'm more than happy to test and give any feedback necessary!

**Comment by sindresorhus** [comment]
I had not actually tested on macOS 10.15 yet. I usually do that right before publishing.

Here's a new build with hotkey and macOS 10.15 fixes: [Plash-2.zip](https://github.com/sindresorhus/Plash/files/6201826/Plash-2.zip)

**Comment by sindresorhus** [comment]
@ced404 I'll keep it in mind. I think it might make sense to add an option for it, but I want to wait and see if anyone else asks for it first.

**Comment by raguay** [comment]
35E90E28-6AF1-496E-883B-45F027C0A0AB

It now gives a bit too much space? but it is readable.

The next/previous hotkeys are working fine for me.

**Comment by sindresorhus** [comment]
> It now gives a bit too much space?

Fixed

**Comment by sindresorhus** [comment]
Thanks for testing, everyone. I'm going to merge this so I can work on some other features. I plan to get this out in an update within a couple of weeks.

**Pull request merged**
